namespace Astronomia;

public static class TextCatalog
{
    public static string Get(Language language, string key)
    {
        return language == Language.English
            ? GetEnglish(key)
            : GetPortuguese(key);
    }

    private static string GetPortuguese(string key)
    {
        return key switch
        {
            "hud.title" => "Simulador de Astronomia",
            "hud.time" => "Tempo",
            "hud.day" => "dia",
            "hud.scale" => "Escala",
            "hud.daysPerSecond" => "dias / segundo",
            "hud.zoom" => "Zoom",
            "language.english" => "Inglês",
            "language.portuguese" => "Português",
            "filters.title" => "Filtros",
            "filters.centerOfMass" => "Centro de massa",
            "topDown.centerSun" => "Centralizar Sol",
            "panel.averageDistance" => "Distância média",
            "panel.orbitalPeriod" => "Período orbital",
            "panel.diameter" => "Diâmetro",
            "panel.mass" => "Massa",
            "panel.relativeMass" => "Massa relativa",
            "panel.rotation" => "Rotação",
            "panel.translation" => "Translação",
            "panel.visiblePhase" => "Fase visível",
            "panel.earth" => "Terra",
            "panel.cameraFollowingOrbit" => "Câmera acompanhando a órbita",
            "panel.freeCameraHint" => "C para voltar ao modo livre",
            "panel.type" => "Tipo",
            "panel.position" => "Posição",
            "panel.solarSystemCenter" => "centro do Sistema Solar",
            "panel.surfaceGravity" => "Gravidade sup.",
            "panel.surfaceTemperature" => "Temp. superfície",
            "panel.cameraFocusedSun" => "Câmera focada no Sol",
            "panel.currentReading" => "Leitura atual",
            "panel.currentSpeed" => "Velocidade atual",
            "panel.acceleration" => "Aceleração",
            "panel.gravitationalForce" => "Força gravitacional",
            "panel.centerMassDistance" => "Dist. centro massa",
            "panel.orbitalEnergy" => "Energia orbital",
            "panel.orbitalContext" => "Contexto orbital",
            "panel.group" => "Grupo",
            "panel.currentDistance" => "Distância atual",
            "panel.visualPosition" => "Posição visual",
            "panel.eccentricity" => "Excentricidade",
            "panel.orbitalInclination" => "Inclinação orbital",
            "panel.degrees" => "graus",
            "panel.orbitalSpeed" => "Velocidade orbital",
            "period.days" => "dias",
            "period.years" => "anos",
            "group.rocky" => "rochoso",
            "group.gasGiant" => "gigante gasoso",
            "group.iceGiant" => "gigante gelado",
            "group.dwarfKuiper" => "planeta anão / Kuiper",
            "group.orbitalBody" => "corpo orbital",
            "depth.frontSun" => "frente do Sol",
            "depth.behindSun" => "atrás do Sol",
            "phase.full" => "cheia",
            "phase.new" => "nova",
            "phase.thinCrescent" => "crescente fina",
            "phase.half" => "meia fase",
            "phase.gibbous" => "gibosa",
            _ => key,
        };
    }

    private static string GetEnglish(string key)
    {
        return key switch
        {
            "hud.title" => "Astronomy Simulator",
            "hud.time" => "Time",
            "hud.day" => "day",
            "hud.scale" => "Scale",
            "hud.daysPerSecond" => "days / second",
            "hud.zoom" => "Zoom",
            "language.english" => "English",
            "language.portuguese" => "Portuguese",
            "filters.title" => "Filters",
            "filters.centerOfMass" => "Center of mass",
            "topDown.centerSun" => "Center Sun",
            "panel.averageDistance" => "Average distance",
            "panel.orbitalPeriod" => "Orbital period",
            "panel.diameter" => "Diameter",
            "panel.mass" => "Mass",
            "panel.relativeMass" => "Relative mass",
            "panel.rotation" => "Rotation",
            "panel.translation" => "Translation",
            "panel.visiblePhase" => "Visible phase",
            "panel.earth" => "Earth",
            "panel.cameraFollowingOrbit" => "Camera following orbit",
            "panel.freeCameraHint" => "C to return to free camera",
            "panel.type" => "Type",
            "panel.position" => "Position",
            "panel.solarSystemCenter" => "center of the Solar System",
            "panel.surfaceGravity" => "Surface gravity",
            "panel.surfaceTemperature" => "Surface temp.",
            "panel.cameraFocusedSun" => "Camera focused on the Sun",
            "panel.currentReading" => "Current reading",
            "panel.currentSpeed" => "Current speed",
            "panel.acceleration" => "Acceleration",
            "panel.gravitationalForce" => "Gravitational force",
            "panel.centerMassDistance" => "Center mass dist.",
            "panel.orbitalEnergy" => "Orbital energy",
            "panel.orbitalContext" => "Orbital context",
            "panel.group" => "Group",
            "panel.currentDistance" => "Current distance",
            "panel.visualPosition" => "Visual position",
            "panel.eccentricity" => "Eccentricity",
            "panel.orbitalInclination" => "Orbital inclination",
            "panel.degrees" => "degrees",
            "panel.orbitalSpeed" => "Orbital speed",
            "period.days" => "days",
            "period.years" => "years",
            "group.rocky" => "rocky",
            "group.gasGiant" => "gas giant",
            "group.iceGiant" => "ice giant",
            "group.dwarfKuiper" => "dwarf planet / Kuiper",
            "group.orbitalBody" => "orbital body",
            "depth.frontSun" => "in front of the Sun",
            "depth.behindSun" => "behind the Sun",
            "phase.full" => "full",
            "phase.new" => "new",
            "phase.thinCrescent" => "thin crescent",
            "phase.half" => "half phase",
            "phase.gibbous" => "gibbous",
            _ => key,
        };
    }
}
